apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: xk6-output-influxdb-v3
  title: xk6-output-influxdb-v3
  description: |
    k6 extension to output real-time test metrics to InfluxDB 3 through its native write API.
  annotations:
    github.com/project-slug: li-zhixin/xk6-output-influxdb-v3
spec:
  type: library
  owner: group:default/k6-core
  lifecycle: production
